### ISSUE TITLE
VMware Compatibility

### ISSUE THREAD

**Issue by G3NSVRV** [arthurchoung/HOTDOG#14]
Hi, I just want to let you know that I was able to run the live ISO by using the following configuration on VMware Workstation 17.5:
- Hardware Compatibility: Workstation 5.x / ESX 3.x [(virtualHW.version = "4")](https://kb.vmware.com/s/article/1003746)
- Guest OS: Other 64-bit
- RAM: 1Gb
- CPU: 1
- Disk: 8GB iSCSi

But I was not able to install it:
```shell
mount : can't find /mnt in /etc/fstab
ERROR : No /sbin/init found on rootdev (or not Mounted). Trouble ahead.
You can try to fix it. Type 'exit' when things are done.

can't access tty; job control turned off
/bin/sh :
```

**Comment by arthurchoung** [comment]
I don't have VMware so all I can do is guess what is happening, but I'm assuming you were able to complete the installation process, but were unable to boot from the disk you just installed?
Are you able to mount the root device manually when it drops to the shell by typing in the appropriate 'mount' command? Which device is supposed to be the root device?

**Comment by arthurchoung** [comment]
Actually my guess is that there might be a missing kernel module for the iSCSI disk. It would need to be added to the initrd. I have no way to test if this is correct though

**Comment by G3NSVRV** [comment]
> Actually my guess is that there might be a missing kernel module for the iSCSI disk. It would need to be added to the initrd. I have no way to test if this is correct though

Yep, That was the problem. I changed to IDE and works perfect. TY
![image](https://github.com/arthurchoung/HOTDOG/assets/11720535/5417b373-76e1-4253-b60f-036ceb6584af)
![image](https://github.com/arthurchoung/HOTDOG/assets/11720535/6b52d67e-3231-49c5-8919-cbe802315dd0)

**Comment by G3NSVRV** [comment]
@arthurchoung you might document this one 👀
