### ISSUE TITLE
Cannot compile: not found 'cc1obj'

### ISSUE THREAD

**Issue by sblendorio** [arthurchoung/HOTDOG#4]
I have Linux Mint 20.3

Here is the condition:

```
sblendorio@sblendorio-laptop:~/github/HOTDOG$ perl build.pl 
execPath: '.'
buildPath: './Build'
find: ‘./misc/’: No such file or directory
find: ‘./external/tidy-html5-5.6.0/src/’: No such file or directory
Compiling linux-homeDir
gcc -c -O3 
    -Werror=implicit-function-declaration
    -Werror=return-type
    -I.
    -I./linux
    -I./lib
    -I./objects
    -I./misc
    -std=c99 -fconstant-string-class=NSConstantString
    -DBUILD_FOUNDATION
    -DBUILD_FOR_LINUX
    -DBUILD_WITH_GNU_PRINTF
    -DBUILD_WITH_GNU_QSORT_R
    -DBUILD_WITH_BGRA_PIXEL_FORMAT
    -o ./Build/Objects/linux-homeDir.o ./linux/linux-homeDir.m 2>>./Build/Logs/linux-homeDir.log

---CUT HERE---
gcc: fatal error: cannot execute ‘cc1obj’: execvp: No such file or directory
compilation terminated.
linux-homeDir: *compileError
```

I did install this, but it did not change the condition:
```
sudo apt install gobjc++-mingw-w64
```

**Comment by arthurchoung** [comment]
An Objective-C compiler needs to be installed. I believe the package name is 'gobjc', so try 'sudo apt install gobjc'. The relevant -devel packages will need to be installed as well, I don't know which ones at the moment.

**Comment by arthurchoung** [comment]
You'll need to install libobjc, I believe the package is libobjc-10-dev depending on the version of gcc you are using. The .a file looks like it will be at /usr/lib/gcc/x86_64-linux-gnu/10/libobjc.a, so you'll need to edit the build.pl file (at the very beginning) to point to the correct path for libobjc.a

**Comment by arthurchoung** [comment]
The command would be something like:

./hotdog "runWindowManager:'enterAmigaMode'"

Have a look at the last line of the file 'xinitrc.hotdogamiga'. 

You can also change the mode using the menu bar, or the root window menu (right click the background).

To integrate further with your system, you can try editing your xsession or xinitrc. I'm not exactly sure how Mint is set up.
